# Generated by Django 4.1.3 on 2022-11-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_userattempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattempts',
            name='Correct_Count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userattempts',
            name='Incorrect_Count',
            field=models.IntegerField(null=True),
        ),
    ]
