# Generated by Django 4.1.3 on 2022-11-18 04:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_userattempts_correct_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattempts',
            name='Completed_Ans',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), default=list, size=None),
        ),
    ]
