# Generated by Django 4.1.3 on 2022-11-18 06:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_userattempts_completed_ans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattempts',
            name='Completed_Ans',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), size=None),
        ),
    ]
